### PR TITLE
Patch for fixing ratio colors (issue #66)

### PR DESCRIPTION
**Pull request by jacksalssome**
Here's my patch for the ratio colors issue. I rearranged and added a few colors and added more out to ratio 1000.

I there was an issue comparing strings, I fixed it my making the value from qBittorrent a float and made the comparison numbers be numbers instead of strings.

### CODE REVIEW

**Comment by Carve** [comment]
> Here's my patch for the ratio colors issue. I rearranged and added a few colors and added more out to ratio 1000.
> 
> I there was an issue comparing strings, I fixed it my making the value from qBittorrent a float and made the comparison numbers be numbers instead of strings.

The only thing I think needs modified is the colors should go from red, orange, yellow, green, blue, indigo, and at the top violet

**Comment by jacksalssome** [comment]
How's it work for you now? Also I got it to keep the 2 decimal places.

**Review by Carve — CHANGES_REQUESTED** [review]
Not a fan of these color changes. There should be 8 max, if the ratio exceeds 1000 ratio then set it to gold aka #d19a66

The base colors in order are:
* Red - #ef596f
* Orange - #be5046
* Yellow - #e5c07b
* Green - #89ca78
* Blue - #61afef
* Indigo - #d55fde
* Violet - #ba5fde

**Comment by jacksalssome** [comment]
Ok, I reverted the colors to those in your repo and added gold. I made it so if ratio is over 100, it will show gold.

**Pull request closed without merging**
